# ====================================================================
# MPO (chains A–D + HEM/CAL) vs CALR (chain E)
# Production config (ab initio rigid-body docking)
# ====================================================================

run_dir = "docking/results_raw/run_keep_hetatm"
mode = "local"
debug = true
concat = 10
queue_limit = 24
ncores = 24       # matches 24 CPU threads change accordingly to system specs

molecules = [
  "data/proteins/processed/MPO_ABCD_hemeCa_clean_fixed.pdb",
  "data/proteins/processed/CALR_chainE_clean.pdb"
]

[topoaa]
autohis = false

[rigidbody]
sampling   = 20000     # full run
tolerance  = 95.0      # allow up to 95% failed models
w_desolv   = 1.0
w_air      = 0.0
w_bsa      = 0.0

[seletop]
select = 400           # keep top models for clustering

[clustfcc]
min_population = 4
clust_cutoff   = 0.6
