run_dir = "docking/results_raw/run_test"
mode = "local"
debug = true
concat = 1
queue_limit = 1

molecules = [
  "data/proteins/processed/MPO_ABCD_hemeCa_clean_fixed.pdb",
  "data/proteins/processed/CALR_chainE_clean.pdb"
]

[topoaa]
autohis = false

[rigidbody]
sampling   = 200
tolerance  = 5.0
w_desolv   = 1.0
w_air      = 0.0
w_bsa      = 0.0

[seletop]
select = 10

[clustfcc]
min_population = 2
clust_cutoff   = 0.6
